### ISSUE TITLE
Executing a function after receiving notification

### ISSUE THREAD

**Issue by nadendlaprasad** [ooper-shlab/HMCatalog-Swift3#10]
Hi, 

Is it possible to execute a function or logic once we receive notification if the app is closed? If not  do we able to receive the updates from iCloud if app is not opened

**Comment by ooper-shlab** [comment]
As far as I know, no, no. By the way, your question seems not to be an issue report of this repository but a general topic of iOS programming. This is not a good place to write such questions, even if you mean HomeKit notifications. Better visit an appropriate place such as [Apple's dev forums](https://forums.developer.apple.com/welcome) or [StackOverflow](https://stackoverflow.com/).

**Comment by nadendlaprasad** [comment]
Yes, you are correct. thank you. do you have any idea about updating accessories in background?
