### ISSUE TITLE
compilation error with Xcode Version 11.4 (11E146)

### ISSUE THREAD

**Issue by VVESTM** [ooper-shlab/HMCatalog-Swift3#11]
Hello,

Since latest update of Xcode, Version 11.4 (11E146), I am not able anymore to compile your sample application.
I have following errors : 
- HMCatalog-Swift3/HMCatalog/Homes/Triggers/Event/Characteristic/CharacteristicTriggerViewController.swift:101:78: Type 'CharacteristicTriggerViewController.Identifiers' has no member ‘conditionCell'
-   HMCatalog-Swift3/HMCatalog/Homes/Triggers/Event/Characteristic/CharacteristicTriggerViewController.swift:114:86: Type 'CharacteristicTriggerViewController.Identifiers' has no member ‘addCell'
-   HMCatalog-Swift3/HMCatalog/Homes/HomeListConfigurationViewController.swift:70:47: Type 'HomeListConfigurationViewController.Identifiers' has no member ‘homeCell'

Any clues ? 

Thanks for your help and for providing this application sample.

**Comment by ooper-shlab** [comment]
Thanks for reporting. I really appreciate your taking time to report this issue.

I cannot assure you when, but I will take some time to investigate this issue and update this repository for Xcode 11.4 and/or report what is wrong, as soon as possible.

Please wait with patience.

**Comment by VVESTM** [comment]
By adding the class name before the statement making the error, it fix the issue.
For example, replace Identifiers.homeCell by HomeListViewController.Identifiers.homeCell

Thanks to @GiovanniVisentini for its hints !
