### ISSUE TITLE
Build issue with Xcode 9 and ios SDK 11.2

### ISSUE THREAD

**Issue by nadendlaprasad** [ooper-shlab/HMCatalog-Swift3#8]
Xcode 9 with ios SDK 11.2 is throwing the " Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1 " the error message while building the project

**Comment by ooper-shlab** [comment]
Thanks for reporting, I will check it when I can make some time for it. Though, I cannot tell or assure you when.

**Comment by nadendlaprasad** [comment]
I fixed this issue. It was causing due to some of the corrupted files in the project. apologies for the trouble

**Comment by ooper-shlab** [comment]
Thanks for reporting. Even if some issue reports might contain mistakes, every report is so valuable for me that I would be able to learn many things. So, I really am sorry that I could not have found enough time to check it. Please do not hesitate to report issues when you found any. Again, thank you.

**Comment by nadendlaprasad** [comment]
Sure. Thank you very much for your support
